### ISSUE TITLE
Have Robot.java extend ITankRobot

### ISSUE THREAD

**Issue by ritikmishra** [Team-2502/RobotCode2018#25]
Seems out of place to make a new anon class extending ITankRobot in PurePursuitCommand.

**Comment by UltraX3** [comment]
Commit [e99cabf](https://github.com/Team-2502/RobotCode2018/commit/e99cabf5712af4d02c0fa3dc4364811e65a25025) changed the structure slightly. The class is now `ITankRobotBounds` instead of `ITankRobot` and should now  only include constant-ish values.

What you suggested is what I originally wanted to do (until I changed it for some reason). After thinking about this for a while, I am still not quite sure what the best option is to do. The biggest benefit for _not_ having `Robot` implement `ITankRobotBounds` is `ITankRobotBounds` could be different in certain situations (ex: max velocity is different for two different trajectory algs). What do you think now?
